name: Show Event Details

on:
  issues:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Show issues event
        run: echo "${{ toJSON(issues) }}"
      - name: Show GitHub context
        run: echo "${{ toJSON(github) }}"
