name: Project Workflow

on:
  push:
  workflow_dispatch:

env:
  NODEJS_VERSION: 18

jobs:
  cache-keys:
    runs-on: ubuntu-latest
    outputs:
      install-key: ${{ runner.os }}-install-artifact-${{ steps.current-date.outputs.CURRENT_DATE }}
    steps:
      - name: Set Current Date
        id: current-date
        run: echo "CURRENT_DATE=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      - name: Show Current Date
        run: echo "${{steps.current-date.outputs.CURRENT_DATE}}"
  install:
    runs-on: ubuntu-latest
    needs: [ cache-keys ]
    steps:
      - name: Install key from 'cache-keys' job output
        run: echo "${{needs.cache-keys.outputs.install-key}}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show code
        run: ls
      - name: Install nodejs '${{ env.NODEJS_VERSION }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Cache install artifacts
        id: cache
        uses: martijnhols/actions-cache/save@v3
        with:
          path: |
            node_modules
          key: ${{needs.cache-keys.outputs.install-key}}
  lint:
    runs-on: ubuntu-latest
    needs: [ install,cache-keys ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use install-artifact from cache
        uses: martijnhols/actions-cache/restore@v3
        with:
          path: |
            node_modules
          key: ${{needs.cache-keys.outputs.install-key}}
          required: true
      - name: Linting
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: [ install,cache-keys ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use install-artifact from cache
        uses: martijnhols/actions-cache/restore@v3
        with:
          path: |
            node_modules
          key: ${{needs.cache-keys.outputs.install-key}}
          required: true
      - name: Linting
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: [ lint,test,cache-keys ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use install-artifact from cache
        uses: martijnhols/actions-cache/restore@v3
        with:
          path: |
            node_modules
          key: ${{needs.cache-keys.outputs.install-key}}
          required: true
      - name: Linting
        run: npm run build
  cleanup:
    runs-on: ubuntu-latest
    needs: [ build,install,cache-keys ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install gh-actions-cache action
        run: gh extension install actions/gh-actions-cache
        env:
          GH_TOKEN: ${{ github.token }}
      - name: List caches
        run: gh actions-cache list
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Cleanup
        run: |
          gh actions-cache delete ${{ needs.cache-keys.outputs.install-key }} --confirm
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Verify caches
        run: gh actions-cache list
        env:
          GH_TOKEN: ${{ github.token }}

