name: Project Workflow

on:
  push:

env:
  NODEJS_VERSION: 18

jobs:
  get-date:
    runs-on: ubuntu-latest
    steps:
      - name: Set Current Date
        id: current-date
        run: echo "CURRENT_DATE=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      - name: Show Current Date
        run: echo "${{steps.current-date.outputs.CURRENT_DATE}}"
  install:
    runs-on: ubuntu-latest
    needs: [ get-date ]
    steps:
      - name: Date from output
        run: |
          echo "${{needs.get-date.outputs.CURRENT_DATE}}"
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Show code
#        run: ls
#      - name: Install nodejs '${{ env.NODJS_VERSION }}'
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ env.NODJS_VERSION }}
#      - name: Install dependencies
#        run: npm ci
#      - name: Cache install artifacts
#        id: cache
#        uses: martijnhols/actions-cache/save@v3
#        with:
#          path: |
#            node_modules
#          key: ${{ runner.os }}-install-artifact-${{ needs.get-date.outputs.current-date }}

#  lint:
#    runs-on: ubuntu-latest
#    needs: [ install ]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Use install-artifact from cache
#        uses: martijnhols/actions-cache/restore@v3
#        with:
#          path: |
#            node_modules
#          key: ${{ runner.os }}-install-artifact-${{ needs.get-date.outputs.current-date }}
#          required: true
#      - name: Linting
#        run: npm run lint
#  test:
#    runs-on: ubuntu-latest
#    needs: [ install ]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Use install-artifact from cache
#        uses: martijnhols/actions-cache/restore@v3
#        with:
#          path: |
#            node_modules
#          key: ${{ runner.os }}-install-artifact-${{ needs.get-date.outputs.current-date }}
#          required: true
#      - name: Linting
#        run: npm run test
#  build:
#    runs-on: ubuntu-latest
#    needs: [ lint,test ]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Use install-artifact from cache
#        uses: martijnhols/actions-cache/restore@v3
#        with:
#          path: |
#            node_modules
#          key: ${{ runner.os }}-install-artifact-${{ needs.get-date.outputs.current-date }}
#          required: true
#      - name: Linting
#        run: npm run build

