name: Pusher Information

on:
  push:

jobs:
  pusher-details:
    runs-on: ubuntu-latest
    steps:
      - name: Show details...
        run: |
          echo "Pusher name: '{{ github.event.pusher.name }}'"
          echo "Pusher email: '{{ github.event.pusher.email }}'"
      - name: View github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
