name: Pusher and Commit Information

on:
  push:

jobs:
  push-info:
    runs-on: ubuntu-latest
    name: push-details
    steps:
      - name: Show pusher details...
        run: |
          echo "## Pusher Details" >> $GITHUB_STEP_SUMMARY
          echo "* Pusher info: '${{ toJSON(github.event.pusher) }}'" >> $GITHUB_STEP_SUMMARY
  commit-info:
    runs-on: ubuntu-latest
    name: commit-details
    steps:
      - name: Show pusher details...
        run: |
          echo "## Pusher Details" >> $GITHUB_STEP_SUMMARY
          echo "* Commit info: '${{ toJSON(github.event.head_commit) }}'" >> $GITHUB_STEP_SUMMARY
  context-info:
    runs-on: ubuntu-latest
    name: context-details
    steps:
      - name: View github context
        run: |
          echo "## GitHub Context Details" >> $GITHUB_STEP_SUMMARY
          echo "$GITHUB_CONTEXT" >> $GITHUB_STEP_SUMMARY
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
