name: Pusher and Commit Information

on:
  push:

jobs:
  details:
    runs-on: ubuntu-latest
    steps:
      - name: Show details...
        run: |
          echo "### Details! :details:" >> $GITHUB_STEP_SUMMARY
          echo "Pusher info: '${{ toJSON(github.event.pusher) }}'"
          echo "Commit info: '${{ toJSON(github.event.head_commit) }}'"
      - name: View github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
